import Head from 'next/head'
import Layout from './components/Layout'


export default function Home() {
  return (
    <>
      <Head>
        <title>Siva</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='flex items-center text-dark w-full min-h-screen'>
        <Layout>
        <h1>Home</h1>        
        </Layout>
      </main>
    </>
  )
}
